import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductserviceService {

  list: object[] = [{
    id: 1,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 2,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 3,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 4,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 5,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 6,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 7,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 8,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 9,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 10,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 11,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 12,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 13,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 14,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 15,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 16,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 17,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 18,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 19,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 20,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 21,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 22,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 23,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 24,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 25,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 26,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 27,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 28,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 29,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 30,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 31,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 32,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 33,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 34,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 35,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 36,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 37,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 38,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 39,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 40,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 41,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 42,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 43,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 44,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 45,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 46,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 47,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 48,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 49,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 50,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: '/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }
  ];

  constructor() { }
}
