import { Injectable } from '@angular/core';
import { Product } from '../model/classes';

@Injectable({
  providedIn: 'root'
})
export class ProductserviceService {

  static list: Product[] = [{
    id: 1,
    catId: 111,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 2,
    catId: 112,
    name: 'Férfi ing kék színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 3,
    catId: 113,
    name: 'Férfi ing piros színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 4,
    catId: 114,
    name: 'Férfi ing rózsaszín színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 5,
    catId: 115,
    name: 'Férfi ing világoskék színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 6,
    catId: 121,
    name: 'Férfi kabát barna színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 7,
    catId: 122,
    name: 'Férfi kabát fekete színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 8,
    catId: 123,
    name: 'Férfi kabát piros színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 9,
    catId: 124,
    name: 'Férfi kabát sárga színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 10,
    catId: 125,
    name: 'Férfi ing zöld színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 11,
    catId: 131,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 12,
    catId: 132,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 13,
    catId: 133,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 14,
    catId: 134,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 15,
    catId: 135,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 16,
    catId: 141,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 17,
    catId: 142,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 18,
    catId: 143,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 19,
    catId: 144,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 20,
    catId: 145,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 21,
    catId: 151,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 22,
    catId: 152,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 23,
    catId: 153,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 24,
    catId: 154,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 25,
    catId: 155,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 26,
    catId: 211,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 27,
    catId: 212,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 28,
    catId: 213,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 29,
    catId: 214,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 30,
    catId: 215,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 31,
    catId: 221,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 32,
    catId: 222,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 33,
    catId: 223,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 34,
    catId: 224,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 35,
    catId: 225,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 36,
    catId: 231,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 37,
    catId: 232,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 38,
    catId: 233,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 39,
    catId: 234,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 40,
    catId: 235,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 41,
    catId: 241,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 42,
    catId: 242,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 43,
    catId: 243,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 44,
    catId: 244,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 45,
    catId: 245,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 46,
    catId: 251,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 47,
    catId: 252,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 48,
    catId: 253,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 49,
    catId: 254,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }, {
    id: 50,
    catId: 255,
    name: 'Férfi ing bézs színű',
    description: 'Jó minőségű pamutból készül bézs színü ing. Kellemes viselet.',
    image: './src/app/assets/img/ferfi-ing-bezs.jpg',
    price: 100,
    stock: 10,
    featured: true,
    active: true,
  }
  ];

  constructor() { }
}
